language: rust
rust:
  - stable

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu

    # OS X
    - env: TARGET=x86_64-apple-darwin
      os: osx

    - env: TARGET=x86_64-pc-windows-gnu