[package]
name = "hamlrs"
version = "0.1.0"
authors = ["Jon Hartwell <jon@dontbreakthebuild.com>"]
license = "MIT"
description = "A Rust library and CLI tool for parsing [Haml](http://haml.info) templates"
respository = "https://github.com/jhartwell/haml-rs"
keywords = ["haml", "templating", "template"]
categories = ["command-line-utilities", "development-tools", "parser-implementations", "template-engine"]
readme = "README.md"
maintenance = { status = "actively-developed" }

[lib]
name = "haml"
path = "src/lib.rs"
test = true
doctest = true
doc = true

[[bin]]
name = "hamlrs"
path = "src/bin/main.rs"


[dependencies]
