[package]
name = "hamlrs"
version = "0.0.1"
authors = ["Jon Hartwell <jon@dontbreakthebuild.com>"]
license = "MIT"
description = "A Rust library and CLI application for parsing [Haml](http://haml.info) template"
homepage = "http://www.haml.rs"
respository = "https://github.com/jhartwell/haml-rs"
keywords = ["haml", "templating", "template"]
categories = ["command-line-utilities", "development-tools", "parser-implementations", "template-engine"]

[lib]
name = "haml"
path = "src/lib.rs"
test = true
doctest = true
doc = true

[[bin]]
name = "hamlrs"
path = "src/bin/main.rs"
test = true
doctest = true
doc = true

[dependencies]
