[package]
name = "hamlrs"
version = "0.0.1"
authors = ["Jon Hartwell <jon@dontbreakthebuild.com>"]
license = "MIT"

[lib]
name = "haml"
path = "src/lib.rs"
test = true
doctest = true
doc = true

[[bin]]
name = "hamlrs"
path = "src/bin/main.rs"
test = true
doctest = true
doc = true

[dependencies]
