[package]
name = "macros"
version = "0.1.0"
authors = ["Jon Hartwell <jon@dontbreakthebuild.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.32"
quote = "0.6.12"
traits = {path = "../traits"}